### ISSUE TITLE
 message: 'Unable to fetch EntityDefinitions. Error: connect ECONNREFUSED 127.0.0.1:443'

### ISSUE THREAD

**Issue by zabaat** [AleksandrRogov/DynamicsWebApi#36]
I cannot make any requests with this lib.

Code is below. My console.log on the adalCallback prints the bearer token completely and all the information looks good.

The error I get is
``` 
[10/12/18 12:06:04 AM] ERROR { Error: connect ECONNREFUSED 127.0.0.1:443
[10/12/18 12:06:04 AM]     at Object._errnoException (util.js:1024:11)
[10/12/18 12:06:04 AM]     at _exceptionWithHostPort (util.js:1046:20)
[10/12/18 12:06:04 AM]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
[10/12/18 12:06:04 AM]   code: 'ECONNREFUSED',
[10/12/18 12:06:04 AM]   syscall: 'connect',
[10/12/18 12:06:04 AM]   address: '127.0.0.1',
[10/12/18 12:06:04 AM]   port: 443 }
```

```var DynamicsWebApi = require('dynamics-web-api');
var AuthenticationContext = require('adal-node').AuthenticationContext;
const secrets = require('../../secrets/secrets.json')
 
//the following settings should be taken from Azure for your application
//and stored in app settings file or in global variables
 
//OAuth Token Endpoint
var authorityUrl = 'https://login.microsoftonline.com/xxxxxxxxx/oauth2/token';
//CRM Organization URL
var resource = 'https://xxxxxx.crm.dynamics.com';
//Dynamics 365 Client Id when registered in Azure
var applicantionId = 'xxxxxxxxxxxxxxxx';
const username = process.env['CRM_USERNAME']
const password = process.env['CRM_PASSWORD']

var AuthenticationContext = require('adal-node').AuthenticationContext;
var adalContext = new AuthenticationContext(authorityUrl);


function acquireToken(dynamicsWebApiCallback) {
    console.log('getting token')
    function adalCallback(error, token) {
        if (!error) {
            console.log(token)
            dynamicsWebApiCallback(token);
        } else {
            console.log('error token', error)
        }
    }
    console.log('resource, username, password, applicantionId', resource, username, password, applicantionId)
    adalContext.acquireTokenWithUsernamePassword(resource, username, password, applicantionId, adalCallback);
}
 
// //create DynamicsWebApi object
var dynamicsWebApi = new DynamicsWebApi({
    webApiUrl: 'https:/nulia.api.crm.dynamics.com/api/data/v9.0',
    onTokenRefresh: acquireToken,
    useEntityNames: true
});
 
const entityKey = '1156A6D0-20C9-E811-A94E-000D3A1F77E8'
dynamicsWebApi.retrieve(entityKey, 'contact', ['fullname']).then(function(record){
    console.log(record)
}).catch(function(error){
    //catch an error
    console.log("ERROR",error)
});```

**Comment by AleksandrRogov** [comment]
Hi @zabaat ,

Your `webApiUrl` is not correct.
Current: `'https:/nulia.api.crm.dynamics.com/api/data/v9.0'`
Should be: `'https://nulia.api.crm.dynamics.com/api/data/v9.0'`

Thanks

**Comment by thargenediad** [comment]
This faulty URL comes from the code example in the README:

`var dynamicsWebApi = new DynamicsWebApi({
    webApiUrl: 'https:/myorg.api.crm.dynamics.com/api/data/v9.0/',
    onTokenRefresh: acquireToken
});`

**Comment by AleksandrRogov** [comment]
I'm going to fix it. Thanks @thargenediad
